"""added client type

Revision ID: 02da0c52583a
Revises: 5f1d95256b45
Create Date: 2026-05-11 16:28:17.314042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02da0c52583a'
down_revision = '5f1d95256b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_primary_personal', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('is_primary_personal')
        batch_op.drop_column('client_type')

    # ### end Alembic commands ###
