"""added client drive folder id

Revision ID: 9ad3165fec0a
Revises: 02da0c52583a
Create Date: 2026-05-12 03:22:49.095131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad3165fec0a'
down_revision = '02da0c52583a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_drive_folder_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('google_drive_folder_id')

    # ### end Alembic commands ###
